# Generated by Django 4.1.7 on 2023-04-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('email', models.EmailField(max_length=500, verbose_name='Email')),
                ('password', models.CharField(max_length=500, verbose_name='Password')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('surname', models.CharField(max_length=500, verbose_name='Surname')),
                ('email', models.EmailField(max_length=500, verbose_name='Email')),
                ('password', models.CharField(max_length=500, verbose_name='Password')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('surname', models.CharField(max_length=500, verbose_name='Surname')),
                ('email', models.EmailField(max_length=500, verbose_name='Email')),
                ('password', models.CharField(max_length=500, verbose_name='Password')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
