# Generated by Django 4.1.7 on 2023-04-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerlist',
            name='password',
            field=models.DateField(max_length=500, verbose_name='Password'),
        ),
    ]
