# Generated by Django 4.1.7 on 2023-04-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_alter_workerlist_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerlist',
            name='password',
            field=models.CharField(max_length=500, verbose_name='Password'),
        ),
    ]
